### ISSUE TITLE
Href 

### ISSUE THREAD

**Issue by DavoodKhoshnood** [SamanZahedi/Portfolio#1]
https://github.com/SamanZahedi/Portfolio/blob/a96fa5dcf2fda8ca9d8e3ace2f6371253e377472/src/components/Sidebar.jsx#L15

Saman aziz! Please change it to href=“#portfolio”

**Comment by DavoodKhoshnood** [comment]
Saman aziz! Please change it to href=“#portfolio”

**Comment by SamanZahedi** [comment]
Chashm Davood aziz! Thank you!
